// examples/react/redirects/src/components/Login.js
import React from "react";

import fakeAuth from "../fakeAuth";

const Login = props => (
  <div>
    <button
      type="button"
      onClick={e => {
        fakeAuth.login();
        const { query } = props.location;
        props.history.navigate(query.next || "/", "REPLACE");
      }}
    >
      Login
    </button>
  </div>
);

export default Login;

// examples/vue/authentication/src/components/Login.vue
<template>
  <div>
    <button
      type='button'
      v-on:click="onClick"
    >
      Login
    </button>
  </div>
</template>

<script>
export default {
  name: "login",
  methods: {
    onClick: function(e) {
      this.$store.commit("login");
      const { query } = this.$curi.response.location;
      this.$router.history.navigate(query.next || "/", "REPLACE");
    }
  }
};
</script>
