// examples/react/transitions/src/components/App.js
import React from "react";
import { useResponse } from "@curi/react-dom";
import { TransitionGroup, CSSTransition } from "react-transition-group";

import NavLinks from "./NavLinks";

export default function App() {
  let { response } = useResponse();

  let { location, body: Body } = response;
  return (
    <div>
      <NavLinks />
      <TransitionGroup>
        <CSSTransition key={location.pathname} classNames="fade" timeout={500}>
          <Body response={response} />
        </CSSTransition>
      </TransitionGroup>
    </div>
  );
}

// examples/vue/transitions/src/components/App.vue
<template>
  <div>
    <NavLinks />
    <transition name="component-fade">
      <component :key="$curi.response.location.pathname" :is="$curi.response.body" />
    </transition>
  </div>
</template>

<script>
import NavLinks from "./NavLinks";
export default {
  name: "app",
  components: { NavLinks }
};
</script>

<style>
.component-fade-enter-active,
.component-fade-leave-active {
  transition: opacity 0.3s ease;
  position: absolute;
}
.component-fade-enter,
.component-fade-leave-to {
  opacity: 0;
  position: absolute;
}
</style>
