// examples/vue/active-links/src/components/ActiveLink.vue
<template>
  <curi-link
    :to="to"
    :params="params"
    :class="classes"
  >
    <slot></slot>
  </curi-link>
</template>

<script>
export default {
  name: "active-links",
  props: ["to", "params", "search", "hash", "state", "partial"],
  computed: {
    classes: function() {
      return this.$router.route.active(
        this.to,
        this.$curi.response,
        this.params,
        this.partial
      )
        ? "active"
        : "";
    }
  }
};
</script>

// examples/svelte/active-links/src/components/ActiveLink.svelte
<Link
  name={name}
  params={params}
  class={className}
>
  <slot></slot>
</Link>

<script>
  import { getRouter, getResponse } from "@curi/svelte";
  import Link from "@curi/svelte/components/Link.svelte";

  const router = getRouter();
  const response = getResponse();

  export let name;
  export let params;
  export let partial = false;

  $: active = router.route.active(name, $response, { params, partial });
  $: className = active ? "active" : "";
</script>
