// examples/vue/active-links/src/components/NavLinks.vue
<template>
  <nav>
    <ul>
      <li>
        <active-link to='Home'>Home</active-link>
      </li>
      <li>
        <active-link to='Contact' :partial="true">Contact</active-link>
        <ul>
          <li>
            <active-link
              to='Method'
              :params="{ method: 'phone' }"
            >
              By Phone
            </active-link>
          </li>
          <li>
            <active-link
              to='Method'
              :params="{ method: 'email' }"
            >
              By Email
            </active-link>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
</template>

<script>
import ActiveLink from "./ActiveLink";

export default {
  name: "nav-links",
  methods: {
    merge: props => {
      props.class = "active";
      return props;
    }
  },
  components: {
    "active-link": ActiveLink
  }
};
</script>

// examples/svelte/active-links/src/components/NavLinks.svelte
<nav>
  <ul>
  <li>
    <ActiveLink name='Home'>Home</ActiveLink>
  </li>
	<li>
		<ActiveLink name='Contact' partial={true}>Contact Us</ActiveLink>
    <ul>
      {#each methods as method}
        <li>
          <ActiveLink name='Method' params={{ method }}>By {method}</ActiveLink>
        </li>
      {/each}
    </ul>
	</li>
  </ul>
</nav>

<script>
  import ActiveLink from "./ActiveLink.svelte";

  let methods = ['email', 'phone'];
</script>
