// packages/svelte/src/Navigating.svelte
<svelte:component this={component} cancel={cancelCallback} />

<script>
  import { onMount, onDestroy } from "svelte";
  import { getRouter } from "@curi/svelte";

  let router = getRouter();

  let cancelCallback;
  let stop;
  let removed = false;

  export let component;

  $: navigating = cancelCallback !== undefined;

  onMount(() => {
    stop = router.cancel(fn => {
      if (!removed) {
        cancelCallback = fn;
      }
    });
  });

  onDestroy(() => {
    if(stop) {
      stop();
    }
  })
</script>

// packages/react-universal/src/Navigating.tsx
import useNavigating from "./hooks/useNavigating";

import { ReactNode } from "react";
import { CancelActiveNavigation } from "@curi/router";

export interface NavigatingProps {
  children(cancel: CancelActiveNavigation | void): ReactNode;
}

export default function Navigating(props: NavigatingProps): ReactNode {
  const cancel = useNavigating();
  return props.children(cancel);
}
