// examples/vue/accessibility/src/components/App.vue
<template>
  <div>
    <Nav />
    <main v-curi-focus="$curi.response" tabIndex="-1">
      <component :is="$curi.response.body" />
    </main>
  </div>
</template>

<script>
import NotFound from "./NotFound";
import Nav from "./Nav";
export default {
  name: "app",
  components: { Nav }
};
</script>

// examples/react/multi-body/src/components/App.js
import React from "react";
import { useResponse } from "@curi/react-dom";

export default function App() {
  const { response } = useResponse();
  const { Main, Menu } = response.body;
  return (
    <div>
      {Menu ? <Menu /> : null}
      {Main ? <Main response={response} /> : null}
    </div>
  );
}
