// examples/vue/async-nav/src/pages/Home.vue
<template>
  <div class="container">
    <curi-link
      name="Movie"
      v-for="movie in $curi.response.data"
      :key="movie.id"
      :params="{ id: movie.id }"
    >
      <template slot-scope="{ navigating }">
        {{ movie.title }}
        <HalfCircleSpinner v-if="navigating" :size="30" color="#444" />
      </template>
    </curi-link>
  </div>
</template>

<script>
import { HalfCircleSpinner } from "epic-spinners";
export default {
  components: {
    HalfCircleSpinner
  }
};
</script>

<style scoped>
.container {
  display: flex;
  flex-flow: column nowrap;
}
a {
  background: #efefef;
  color: #444;
  margin: 5px 0;
  display: flex;
  flex-flow: row nowrap;
  justify-content: space-between;
  align-items: flex-end;
  padding: 5px;
  border-radius: 5px;
  height: 30px;
  width: 250px;
}
</style>

// examples/svelte/async-nav/src/pages/Home.svelte
<div class="container">
  {#each $response.data as movie (movie.id)}
    <AsyncLink
      name="Movie"
      params={{ id: movie.id }}
      wrapper={SpinWhileNavigating}
      forward={{ class: "link" }}
    >
      {movie.title}
    </AsyncLink>
  {/each}
</div>

<script>
  import { getResponse } from "@curi/svelte";
  import AsyncLink from "@curi/svelte/components/AsyncLink.svelte";
  import SpinWhileNavigating from "../components/SpinWhileNavigating.svelte";

  const response = getResponse();
</script>

<style>
  .container {
    display: flex;
    flex-flow: column nowrap;
  }

  .link {
    background: #efefef;
    color: #444;
    margin: 5px 0;
    display: flex;
    flex-flow: row nowrap;
    justify-content: space-between;
    align-items: flex-end;
    padding: 5px;
    border-radius: 5px;
    height: 30px;
    width: 250px;
  }
</style>
