// examples/vue/basic/src/components/App.vue
<template>
  <div>
    <Nav />
    <component :is="cmp" />
  </div>
</template>

<script>
  import NotFound from './NotFound';
  import Nav from './Nav';
  export default {
    name: 'app',
    computed: {
      cmp() {
        return this.$curi.response.body || NotFound
      }
    },
    components: { Nav }
  }
</script>

// examples/react/basic/src/components/App.js
import React from "react";
import { useResponse } from "@curi/react-dom";

import NavLinks from "./NavLinks";

export default function App() {
  let { response } = useResponse();

  let { body: Body } = response;
  return (
    <div>
      <NavLinks />
      <Body response={response} />
    </div>
  );
}
