// examples/vue/transitions/src/components/NavLinks.vue
<template>
  <nav>
    <ul>
      <li><curi-link name="Home">Home</curi-link></li>
      <li>
        <curi-link name="Contact">Contact</curi-link>
        <ol>
          <li>
            <curi-link name="Method" :params="{ method: 'phone' }"
              >By Phone</curi-link
            >
          </li>
          <li>
            <curi-link name="Method" :params="{ method: 'email' }"
              >By Email</curi-link
            >
          </li>
          <li>
            <curi-link name="Method" :params="{ method: 'mail' }"
              >By Mail</curi-link
            >
          </li>
        </ol>
      </li>
    </ul>
  </nav>
</template>

<script>
export default {
  name: "nav-links"
};
</script>

// examples/react/basic/src/components/NavLinks.js
import React from 'react';
import { Link } from '@curi/react';

const NavLinks = () => (
  <nav>
    <ul>
      <li>
        <Link to='Home'>Home</Link>
      </li>
      <li>
        <Link to='Contact'>Contact</Link>
        <ul>
          <li>
            <Link
              to='Method'
              params={{ method: 'phone' }}
            >
              By Phone
            </Link>
          </li>
          <li>
            <Link
              to='Method'
              params={{ method: 'email' }}
            >
              By Email
            </Link>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
);

export default NavLinks;
