// examples/react/accessibility/src/components/App.js
import React from "react";
import { useCuri, useNavigationFocus } from "@curi/react-dom";

import NavLinks from "./NavLinks";

export default function App() {
  const { response } = useCuri();
  const ref = React.useRef(null);
  useNavigationFocus(ref);

  const { body: Body } = response;
  return (
    <div>
      <NavLinks />
      <main tabIndex={-1} ref={ref}>
        <Body params={response.params} />
      </main>
    </div>
  );
}

// examples/vue/accessibility/src/components/App.vue
<template>
  <div>
    <Nav />
    <main v-curi-focus="$curi.response" tabIndex="-1">
      <component :is="$curi.response.body" />
    </main>
  </div>
</template>

<script>
import NotFound from "./NotFound";
import Nav from "./Nav";
export default {
  name: "app",
  components: { Nav }
};
</script>
