// examples/vue/modal/src/components/Detail.vue
<template>
  <div>
    <div
      class='thumbnail'
      :style='{ background: response.params.color || "#666" }'
    />
    <p>Previewing paint color {{response.params.color}}</p>
  </div>
</template>

<script>
export default {
  name: "Detail",
  props: ["response"]
};
</script>

<style>
.thumbnail {
  width: 80%;
  height: 25%;
  min-height: 200px;
  background: #666;
}
</style>

// examples/react/modal/src/components/Detail.js
import React from "react";

let Detail = ({ response }) => (
  <div>
    <div
      style={{
        width: "80%",
        height: "25%",
        minHeight: 200,
        background: response.params.color || "#666"
      }}
    />
    <p>Previewing paint color {response.params.color}</p>
  </div>
);

export default Detail;
