// examples/vue/modal/src/components/NavLinks.vue
<template>
  <nav>
    <ul>
      <li>
        <curi-link to="Home">Home</curi-link>
      </li>
      <li>
        Paints
        <ol>
          <li>
            <curi-link
              to="Product"
              :params='{ color: "DarkSlateBlue" }'
              :details='{ state: { name: "Dark Slate Blue" } }'
            >
              Dark Slate Blue
            </curi-link>
          </li>
          <li>
            <curi-link
              to="Product"
              :params='{ color: "SeaGreen" }'
              :details='{ state: { name: "Sea Green" } }'
            >
              Sea Green
            </curi-link>
          </li>
          <li>
            <curi-link
              to="Product"
              :params='{ color: "Crimson" }'
              :details='{ state: { name: "Crimson" } }'
            >
              Crimson
            </curi-link>
          </li>
        </ol>
      </li>
    </ul>
  </nav>
</template>

<script>
export default {
  name: "Navcuri-links"
};
</script>

// examples/react/modal/src/components/NavLinks.js
import React from "react";
import { Link } from "@curi/react";

const NavLinks = () => (
  <nav>
    <ul>
      <li>
        <Link to="Home">Home</Link>
      </li>
      <li>
        Paints
        <ol>
          <li>
            <Link
              to="Product"
              params={{ color: "DarkSlateBlue" }}
              details={{ state: { name: "Dark Slate Blue" } }}
            >
              Dark Slate Blue
            </Link>
          </li>
          <li>
            <Link
              to="Product"
              params={{ color: "SeaGreen" }}
              details={{ state: { name: "Sea Green" } }}
            >
              Sea Green
            </Link>
          </li>
          <li>
            <Link
              to="Product"
              params={{ color: "Crimson" }}
              details={{ state: { name: "Crimson" } }}
            >
              Crimson
            </Link>
          </li>
        </ol>
      </li>
    </ul>
  </nav>
);

export default NavLinks;
