// examples/vue/transitions/src/components/NavLinks.vue
<template>
  <nav>
    <ul>
      <li><curi-link name="Home">Home</curi-link></li>
      <li>
        <curi-link name="Contact">Contact</curi-link>
        <ol>
          <li>
            <curi-link name="Method" :params="{ method: 'phone' }"
              >By Phone</curi-link
            >
          </li>
          <li>
            <curi-link name="Method" :params="{ method: 'email' }"
              >By Email</curi-link
            >
          </li>
          <li>
            <curi-link name="Method" :params="{ method: 'mail' }"
              >By Mail</curi-link
            >
          </li>
        </ol>
      </li>
    </ul>
  </nav>
</template>

<script>
export default {
  name: "nav-links"
};
</script>

// examples/react/transitions/src/components/NavLinks.js
import React from "react";
import { Link } from "@curi/react-dom";

const NavLinks = () => (
  <nav>
    <ul>
      <li>
        <Link name="Home">Home</Link>
      </li>
      <li>
        <Link name="Contact">Contact</Link>
        <ol>
          <li>
            <Link name="Method" params={{ method: "phone" }}>
              By Phone
            </Link>
          </li>
          <li>
            <Link name="Method" params={{ method: "email" }}>
              By Email
            </Link>
          </li>
          <li>
            <Link name="Method" params={{ method: "mail" }}>
              By Mail
            </Link>
          </li>
        </ol>
      </li>
    </ul>
  </nav>
);

export default NavLinks;
