// examples/vue/async-nav/src/components/Controls.vue
<template>
  <div class="controls">
    <p>
      Use the controls to adjust the data load time and to clear the cache
      of loaded data.
    </p>
    <div>
      <label htmlFor="delay">Delay: {{this.delay}}</label>
      <input
        type="range"
        :value="this.delay"
        min="0"
        max="5000"
        step="500"
        v-on:change="this.delayHandler"
      />
    </div>
    <div>
      <button type="button" v-on:click="this.clearCache">
        Clear Cache
      </button>
    </div>
  </div>
</template>

<script>
import { delay } from "../api";
import cache from "../cache";

export default {
  data() {
    return {
      delay: delay()
    };
  },
  methods: {
    delayHandler(event) {
      const value = delay(parseInt(event.target.value, 10));
      this.delay = value;
    },
    clearCache() {
      cache.reset();
    }
  }
};
</script>

<style scoped>
.controls {
  border: 1px solid #444;
  padding: 5px;
}
</style>

// examples/svelte/async-nav/src/components/Controls.svelte
<div class="controls">
  <p>
    Use the controls to adjust the data load time and to clear the cache
    of loaded data.
  </p>
  <div>
    <label for="delayRange">Delay: {delay}</label>
    <input
      type="range"
      id="delayRange"
      bind:value={delay}
      min="0"
      max="5000"
      step="500"
      on:input={delayHandler}
    />
  </div>
  <div>
    <button type="button" on:click={clearCache}>
      Clear Cache
    </button>
  </div>
</div>

<script>
  import { delay as delayAPI } from "../api";
  import cache from "../cache";

  let delay = delayAPI();

  function delayHandler(event) {
    delayAPI(parseInt(event.target.value, 10));
  }

  function clearCache() {
    cache.reset();
  }
</script>

<style>
  .controls {
    border: 1px solid #444;
    padding: 5px;
  }
</style>
