// examples/vue/active-links/src/components/NavLinks.vue
<template>
  <nav>
    <ul>
      <li>
        <curi-link to='Home' :active="{ merge }">Home</curi-link>
      </li>
      <li>
        <curi-link to='Contact' :active="{ merge, partial: true }">Contact</curi-link>
        <ul>
          <li>
            <curi-link
              to='Method'
              :active="{ merge }"
              :params="{ method: 'phone' }"
            >
              By Phone
            </curi-link>
          </li>
          <li>
            <curi-link
              to='Method'
              :active="{ merge }"
              :params="{ method: 'email' }"
            >
              By Email
            </curi-link>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
</template>

<script>
  export default {
    name: 'nav-links',
    methods: {
      merge: (props) => {
        props.class = 'active';
        return props;
      }
    }
  };
</script>

// examples/react/active-links/src/components/NavLinks.js
import React from "react";
import { Link } from "@curi/react";

const merge = props => {
  props.className = "active";
  return props;
};

const NavLinks = () => (
  <nav>
    <ul>
      <li>
        <Link to="Home" active={{ merge }}>
          Home
        </Link>
      </li>
      <li>
        <Link to="Contact" active={{ merge, partial: true }}>
          Contact
        </Link>
        <ul>
          <li>
            <Link to="Method" active={{ merge }} params={{ method: "phone" }}>
              By Phone
            </Link>
          </li>
          <li>
            <Link to="Method" active={{ merge }} params={{ method: "email" }}>
              By Email
            </Link>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
);

export default NavLinks;
