// examples/svelte/async-nav/src/pages/Movie.svelte
{#if error}
  <p>The requested movie could not be found</p>
{:else if movie}
  <h1>{movie.title}</h1>
{/if}
<Link name="Home">Home</Link>

<script>
  import { getResponse } from "@curi/svelte";
  import Link from "@curi/svelte/components/Link.svelte";

  const response = getResponse();

  $: error = $response.data.error;
  $: movie = $response.data.movie;
</script>

// examples/react/async-nav/src/pages/Movie.js
import React from "react";
import { Link } from "@curi/react-dom";

let Movie = ({ response }) => {
  let { error, movie } = response.data;
  if (error) {
    return (
      <div>
        <p>Sorry, but the movie could not be found.</p>
        <Link to="Home">Home</Link>
      </div>
    );
  }
  return (
    <div>
      <h1>{movie.title}</h1>
      <Link name="Home">Home</Link>
    </div>
  );
};

export default Movie;
