// examples/svelte/breadcrumbs/src/components/Breadcrumbs.svelte
<ul className="breadcrumbs">
  {#each ancestors as name (name)}
    <li>
      <Link name={name} params={params}>
        {router.route.title(name, params)}
      </Link>
    </li>
  {/each}
</ul>

<script>
  import { getRouter } from "@curi/svelte";
  import Link from "@curi/svelte/components/Link.svelte";

  export let name;
  export let params;

  const router = getRouter();

  let ancestors = router.route.ancestors(name).reverse();
</script>

// examples/vue/breadcrumbs/src/components/Breadcrumbs.vue
<template>
  <ul class='breadcrumbs'>
    <li v-for="a in ancestors" :key="a">
      <curi-link :to="a" :params="params">{{title(a)}}</curi-link>
    </li>
  </ul>
</template>

<script>
export default {
  name: "breadcrumbs",
  props: ["name", "params"],
  computed: {
    ancestors() {
      return this.$router.route.ancestors(this.name).reverse();
    }
  },
  methods: {
    title(a) {
      return this.$router.route.title(a, this.params);
    }
  }
};
</script>
