// examples/svelte/breadcrumbs/src/components/Product.svelte
<div>
  <Breadcrumbs name="Product" params={params} />
  <h1>{product.name}</h1>
  <p>{product.description}</p>
</div>

<script>
  import { getResponse } from "@curi/svelte";
  import Breadcrumbs from "./Breadcrumbs.svelte";

  const response = getResponse();

  $: params = $response.params;
  $: product = $response.data.product;
</script>

// examples/vue/breadcrumbs/src/components/Product.vue
<template>
  <div>
    <breadcrumbs name='Product' :params="$curi.response.params" />
    <div v-if='$curi.response.error'>
      {{$curi.response.error}}
    </div>
    <div v-else>
      <h1>{{$curi.response.data.name}}</h1>
      <p>
        {{$curi.response.data.description}}
      </p>
    </div>
  </div>
</template>

<script>
  import Breadcrumbs from './Breadcrumbs';
  export default {
    name: 'product',
    components: { breadcrumbs: Breadcrumbs }
  }
</script>
