// examples/svelte/breadcrumbs/src/components/Products.svelte
<div>
  <h1>Products Page</h1>
  <h2>Categories</h2>
  <ul>
    {#each categories as category (category)}
      <li>
        <Link name="Category" params={{ category }}>
          {title(categoryRoute, { category })}
        </Link>
      </li>
    {/each}
  </ul>
</div>


<script>
  import { getRouter, getResponse } from "@curi/svelte";
  import Link from "@curi/svelte/components/Link.svelte";
  import title from "../titleInteraction";

  const router = getRouter();
  const response = getResponse();

  const categoryRoute = router.route("Category");

  $: categories = $response.data.categories;
</script>

// examples/vue/breadcrumbs/src/components/Products.vue
<template>
  <div>
    <h1>Products Page</h1>
    <h2>Categories</h2>
    <ul>
      <li v-for="category in $curi.response.data" :key="category">
        <curi-link name="Category" :params="{ category }">
          {{ title(category) }}
        </curi-link>
      </li>
    </ul>
  </div>
</template>

<script>
import title from "../titleInteraction";

export default {
  name: "products",
  methods: {
    title(category) {
      let categoryRoute = this.$router.route("Category");
      return title(categoryRoute, { category });
    }
  }
};
</script>
