// examples/react/breadcrumbs/src/components/Products.js
import React from "react";
import { Link } from "@curi/react-dom";

const Products = ({ response: { data }, router }) => (
  <div>
    <h1>Products Page</h1>
    <h2>Categories</h2>
    <ul>
      {data.map(category => (
        <li key={category}>
          <Link name="Category" params={{ category }}>
            {router.route.title("Category", { category })}
          </Link>
        </li>
      ))}
    </ul>
  </div>
);

export default Products;

// examples/vue/breadcrumbs/src/components/Products.vue
<template>
  <div>
    <h1>Products Page</h1>
    <h2>Categories</h2>
    <ul>
      <li v-for="category in $curi.response.data" :key="category">
        <curi-link to="Category" :params="{ category }">
          {{title(category)}}
        </curi-link>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: "products",
  methods: {
    title(category) {
      return this.$router.route.title("Category", { category });
    }
  }
};
</script>
