// examples/react/async-nav/src/components/App.js
import React from "react";
import { useCuri } from "@curi/react-dom";

import Cancel from "./Cancel";

export default function App() {
  const { response } = useCuri();

  const { body: Body, data } = response;

  return (
    <React.Fragment>
      <Cancel />
      <Body response={response} />
    </React.Fragment>
  );
}

// examples/breadcrumbs-vue/src/components/App.vue
<template>
  <div>
    <component
      :is="cmp"
      :data="$curi.response.data"
      :params="$curi.response.params"
    />
  </div>
</template>

<script>
  import NotFound from './NotFound';
  export default {
    name: 'app',
    computed: {
      cmp() {
        return this.$curi.response.body || NotFound
      }
    }
  }
</script>
