// examples/react/breadcrumbs/src/components/Breadcrumbs.js
import React from "react";
import { Curious, Link } from "@curi/react";

const Breadcrumbs = ({ name, params }) => (
  <Curious
    render={({ router }) => (
      <ul className="breadcrumbs">
        {router.addons
          .ancestors(name)
          .reverse()
          .map(a => (
            <li key={a}>
              <Link to={a} params={params}>
                {router.addons.title(a, params)}
              </Link>
            </li>
          ))}
      </ul>
    )}
  />
);

export default Breadcrumbs;

// examples/breadcrumbs-vue/src/components/Breadcrumbs.vue
<template>
  <ul class='breadcrumbs'>
    <li v-for="a in ancestors" :key="a">
      <curi-link :to="a" :params="params">{{title(a)}}</curi-link>
    </li>
  </ul>
</template>

<script>
  export default {
    name: 'breadcrumbs',
    props: ['name', 'params'],
    computed: {
      ancestors() {
        return this.$curi.addons.ancestors(this.name).reverse();
      }
    },
    methods: {
      title(a) {
        return this.$curi.addons.title(a, this.params);
      }
    }
  }
</script>
