// examples/react/breadcrumbs/src/components/Category.js
import React from "react";
import { Link } from "@curi/react";
import Breadcrumbs from "./Breadcrumbs";

const Category = ({ router, response: { params, data: products } }) => (
  <div>
    <Breadcrumbs name="Category" params={params} />
    <h1>{params.category}</h1>
    <p>List of products</p>
    <ul>
      {products.map(p => {
        const productParams = { ...params, productID: p.id };
        return (
          <li key={p.id}>
            <Link to="Product" params={productParams}>
              {router.addons.title("Product", { name: p.name })}
            </Link>
          </li>
        );
      })}
    </ul>
  </div>
);

export default Category;

// examples/breadcrumbs-vue/src/components/Category.vue
<template>
  <div>
    <h1>{{$curi.response.params.category}}</h1>
    <breadcrumbs name='Category' :params="$curi.response.params" />
    <p>List of products</p>
    <ul>
      <li v-for="product in $curi.response.data" :key="product.id">
        <curi-link to='Product' :params="linkParams(product.id)">
          {{title(product.name)}}
        </curi-link>
      </li>
    </ul>

  </div>
</template>

<script>
  import Breadcrumbs from './Breadcrumbs';

  export default {
    name: 'contact-method',
    methods: {
      title(name) {
        return this.$curi.config.addons.title('Product', { name });
      },
      linkParams(productID) {
        return { ...this.$curi.response.params, productID };
      }
    },
    components: { breadcrumbs: Breadcrumbs }
  };
</script>
