// examples/react/breadcrumbs/src/components/Products.js
import React from 'react';
import { Link, curious } from '@curi/react';

const Products = ({ data, curi }) => (
  <div>
    <h1>Products Page</h1>
    <h2>Categories</h2>
    <ul>
      {
        data.map(category => (
          <li key={category}>
            <Link to='Category' params={{ category }}>
              {curi.addons.title('Category', { category })}
            </Link>
          </li>
        ))
      }
    </ul>
  </div>
);

export default curious(Products);

// examples/breadcrumbs-vue/src/components/Products.vue
<template>
  <div>
    <h1>Products Page</h1>
    <h2>Categories</h2>
    <ul>
      <li v-for="category in data" :key="category">
        <curi-link to="Category" :params="{ category }">
          {{title(category)}}
        </curi-link>
      </li>
    </ul>
  </div>
</template>

<script>
  export default {
    name: 'products',
    props: ['data'],
    methods: {
      title(category) {
        return this.$curi.addons.title('Category', { category });
      }
    }
  }
</script>
