// examples/svelte/breadcrumbs/src/components/Product.svelte
<div>
  <Breadcrumbs name="Product" params={params} />
  <h1>{product.name}</h1>
  <p>{product.description}</p>
</div>

<script>
  import { getResponse } from "@curi/svelte";
  import Breadcrumbs from "./Breadcrumbs.svelte";

  const response = getResponse();

  $: params = $response.params;
  $: product = $response.data.product;
</script>

// examples/breadcrumbs-vue/src/components/Product.vue
<template>
  <div>
    <breadcrumbs name='Product' :params="params" />
    <h1>{{data.name}}</h1>
    <p>
      {{data.description}}
    </p>
  </div>
</template>

<script>
  import Breadcrumbs from './Breadcrumbs';
  export default {
    name: 'product',
    props: ['data', 'params'],
    components: { breadcrumbs: Breadcrumbs }
  }
</script>
