// examples/react/redirects/src/components/App.js
import React from "react";
import { useResponse } from "@curi/react-dom";

import NavLinks from "./NavLinks";

export default function App() {
  const { response } = useResponse();

  const { body: Body } = response;
  return (
    <div>
      <NavLinks />
      <Body response={response} />
    </div>
  );
}

// examples/vue/modal/src/components/App.vue
<template>
  <div>
    <NavLinks />
    <Display
      :response="$curi.response"
      :navigation="$curi.navigation"
    />
  </div>
</template>

<script>
import NavLinks from "./NavLinks";
import Display from "./Display";
export default {
  name: "App",
  components: {
    NavLinks,
    Display
  }
};
</script>

<style>
body {
  min-height: 100vh;
}
</style>
