// examples/react/modal/src/components/Product.js
import React from "react";
import { Link } from "@curi/react";

const Preview = ({ color }) => (
  <div
    style={{
      width: 20,
      height: 20,
      background: color || "#666"
    }}
  />
);

const Product = ({ response }) => (
  <div>
    Paint color: {response.location.state.name || "Unknown"}
    <Preview color={response.params.color} />
    <Link
      to="Product Detail"
      params={response.params}
      details={{ state: { modal: true, name: "Dark Slate Blue" } }}
    >
      Detail View
    </Link>
  </div>
);

export default Product;

// examples/vue/modal/src/components/Product.vue
<template>
  <div>
    Paint color: {{response.location.state.name || "Unknown"}}
    <Preview :color="response.params.color" />
    <curi-link
      to="Product Detail"
      :params="response.params"
      :details='{ state: { modal: true } }'
    >
      Detail View
    </curi-link>
  </div>
</template>

<script>
import Preview from "./Preview";

export default {
  name: "Product",
  props: ["response"],
  components: { Preview }
};
</script>
