// examples/svelte/basic/src/components/Nav.svelte
<nav>
  <ul>
  <li>
    <Link name='Home'>Home</Link>
  </li>
	<li>
		<Link name='Contact'>Contact Us</Link>
    <ul>
      {#each methods as method}
        <li>
          <Link name='Method' params={{ method }}>By {method}</Link>
        </li>
      {/each}
    </ul>
	</li>
  </ul>
</nav>

<script>
  import Link from "@curi/svelte/components/Link.svelte";

  let methods = ['email', 'phone'];
</script>

// examples/basic-vue/src/components/Nav.vue
<template>
  <nav>
    <ul>
      <li>
        <curi-link to="Home">Home</curi-link>
      </li>
      <li>
        <curi-link to="Contact">Contact</curi-link>
        <ul>
          <li v-for="m in methods">
            <curi-link to="Method" :params="m">{{m.method}}</curi-link>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
</template>

<script>
  export default {
    name: 'app-nav',
    data: function() {
      return {
        methods: [
          { method: 'Phone' },
          { method: 'Email' },
          { method: 'Fax' }
        ]
      }
    }
  };
</script>
