// examples/vue/breadcrumbs/src/components/Category.vue
<template>
  <div>
    <breadcrumbs name="Category" :params="$curi.response.params" />
    <h1>{{ $curi.response.params.category }}</h1>
    <p>List of products</p>
    <ul>
      <li v-for="product in $curi.response.data" :key="product.id">
        <curi-link name="Product" :params="linkParams(product.id)">
          {{ title(product.name) }}
        </curi-link>
      </li>
    </ul>
  </div>
</template>

<script>
import Breadcrumbs from "./Breadcrumbs";
import title from "../titleInteraction";

export default {
  name: "contact-method",
  methods: {
    title(name) {
      let productRoute = this.$router.route("Product");
      return title(productRoute, { name });
    },
    linkParams(productID) {
      return { ...this.$curi.response.params, productID };
    }
  },
  components: { breadcrumbs: Breadcrumbs }
};
</script>

// examples/svelte/breadcrumbs/src/components/Category.svelte
<div>
  <Breadcrumbs name="Category" params={params} />
  <h1>{params.category}</h1>
  <p>List of products</p>
  <ul>
    {#each products as product (product.id)}
      <li>
        <Link name="Product" params={{ ...params, productID: product.id }}>
          {title(productRoute, { name: product.name })}
        </Link>
      </li>
    {/each}
  </ul>
</div>

<script>
  import { getRouter, getResponse } from "@curi/svelte";
  import Link from "@curi/svelte/components/Link.svelte";
  import Breadcrumbs from "./Breadcrumbs.svelte";
  import title from "../titleInteraction";

  let router = getRouter();
  let response = getResponse();

  let productRoute = router.route("Product");

  $: params = $response.params;
  $: products = $response.data.products;
</script>
