// examples/vue/redirects/src/components/Login.vue
<template>
  <div>
    <button type="button" v-on:click="onClick">
      Login
    </button>
  </div>
</template>

<script>
export default {
  name: "login",
  methods: {
    onClick: function(e) {
      this.$store.commit("login");
      const { query } = this.$curi.response.location;
      this.$router.navigate({ url: query.next || "/", method: "replace" });
    }
  }
};
</script>

// examples/svelte/redirects/src/components/Login.svelte
<div>
  <button type="button" on:click={loginAndRedirect}>
    Login
  </button>
</div>

<script>
  import { getRouter, getResponse } from "@curi/svelte";
  import fakeAuth from "../fakeAuth";

  const router = getRouter();
  const response = getResponse();

  function loginAndRedirect() {
    fakeAuth.login();
    const { query } = $response.response.location;
    $router.navigate({ url: query.next || "/", method: "replace" });
  }
</script>
