// examples/react/redirects/src/components/Login.js
import React from "react";
import { useRouter } from "@curi/react-dom";

import fakeAuth from "../fakeAuth";

let Login = ({ response }) => {
  let router = useRouter();
  return (
    <div>
      <button
        type="button"
        onClick={e => {
          fakeAuth.login();
          let { state } = response.location;
          let url = router.url(
            state && state.next ? state.next : { name: "Home" }
          );
          router.navigate({
            url,
            state,
            method: "replace"
          });
        }}
      >
        Login
      </button>
    </div>
  );
};

export default Login;

// examples/svelte/redirects/src/components/Login.svelte
<div>
  <button type="button" on:click={loginAndRedirect}>
    Login
  </button>
</div>

<script>
  import { getRouter, getResponse } from "@curi/svelte";
  import fakeAuth from "../fakeAuth";

  const router = getRouter();
  const response = getResponse();

  function loginAndRedirect() {
    fakeAuth.login();
    const { query } = $response.response.location;
    $router.navigate({ url: query.next || "/", method: "replace" });
  }
</script>
