// examples/react/redirects/src/components/NavLinks.js
import React from "react";
import { Link } from "@curi/react-dom";

import fakeAuth from "../fakeAuth";

const NavLinks = () => (
  <nav>
    <ul>
      <li>
        <Link name="Home">Home</Link>
      </li>
      <li>
        <Link name="Protected">Protected</Link>
      </li>
      <li>
        {fakeAuth.authenticated() ? (
          <Link name="Logout">Logout</Link>
        ) : (
          <Link name="Login">Login</Link>
        )}
      </li>
    </ul>
  </nav>
);

export default NavLinks;

// examples/svelte/redirects/src/components/NavLinks.svelte
<nav>
  <ul>
    <li>
      <Link name="Home">Home</Link>
    </li>
    <li>
      <Link name="Protected">Protected</Link>
    </li>
    <li>
      {#if authenticated}
        <Link name="Logout">Logout</Link>
      {:else}
        <Link name="Login">Login</Link>
      {/if}
    </li>
  </ul>
</nav>

<script>
  import Link from "@curi/svelte/components/Link.svelte";
  import fakeAuth from "../fakeAuth";

  $: authenticated = $fakeAuth;
</script>
