// examples/vue/authentication/src/components/NavLinks.vue
<template>
  <nav>
    <ul>
      <li><curi-link to='Home'>Home</curi-link></li>
      <li><curi-link to='Protected'>Protected</curi-link></li>
      <li>
        <curi-link v-if="$store.state.user" to='Logout'>Logout</curi-link>
        <curi-link v-else to='Login'>Login</curi-link>
      </li>
    </ul>
  </nav>
</template>

<script>
  export default {
    name: 'nav-links'
  };
</script>

// examples/svelte/redirects/src/components/NavLinks.svelte
<nav>
  <ul>
    <li>
      <Link name="Home">Home</Link>
    </li>
    <li>
      <Link name="Protected">Protected</Link>
    </li>
    <li>
      {#if authenticated}
        <Link name="Logout">Logout</Link>
      {:else}
        <Link name="Login">Login</Link>
      {/if}
    </li>
  </ul>
</nav>

<script>
  import Link from "@curi/svelte/components/Link.svelte";
  import fakeAuth from "../fakeAuth";

  $: authenticated = $fakeAuth;
</script>
