// examples/svelte/breadcrumbs/src/components/Product.svelte
<div>
  <Breadcrumbs name="Product" params={params} />
  <h1>{product.name}</h1>
  <p>{product.description}</p>
</div>

<script>
  import { getResponse } from "@curi/svelte";
  import Breadcrumbs from "./Breadcrumbs.svelte";

  const response = getResponse();

  $: params = $response.params;
  $: product = $response.data.product;
</script>

// examples/react/mobx/src/components/Product.js
import React from "react";
import { inject, observer } from "mobx-react";

const Product = ({ products, response }) => {
  const product = products[response.params.id];
  return product ? (
    <div>Product: {product.name}</div>
  ) : (
    <div>No product with id {response.params.id} was found</div>
  );
};

export default inject("products")(observer(Product));
