// examples/vue/breadcrumbs/src/components/Breadcrumbs.vue
<template>
  <ul class='breadcrumbs'>
    <li v-for="a in ancestors" :key="a">
      <curi-link :to="a" :params="params">{{title(a)}}</curi-link>
    </li>
  </ul>
</template>

<script>
export default {
  name: "breadcrumbs",
  props: ["name", "params"],
  computed: {
    ancestors() {
      return this.$router.route.ancestors(this.name).reverse();
    }
  },
  methods: {
    title(a) {
      return this.$router.route.title(a, this.params);
    }
  }
};
</script>

// examples/react/breadcrumbs/src/components/Breadcrumbs.js
import React from "react";
import { Curious, Link } from "@curi/react";

const Breadcrumbs = ({ name, params }) => (
  <Curious>
    {({ router }) => (
      <ul className="breadcrumbs">
        {router.route
          .ancestors(name)
          .reverse()
          .map(a => (
            <li key={a}>
              <Link to={a} params={params}>
                {router.route.title(a, params)}
              </Link>
            </li>
          ))}
      </ul>
    )}
  </Curious>
);

export default Breadcrumbs;
