// packages/svelte/components/Link.svelte
<a {...$$restProps} href="{url}" on:click="{handleClick}">
  <slot></slot>
</a>

<script>
  import { getRouter } from "@curi/svelte";

  let router = getRouter();

  let canNavigate = (event, target) => {
    return (
      !event.defaultPrevented &&
      !target &&
      event.button === 0 &&
      !(event.metaKey || event.altKey || event.ctrlKey || event.shiftKey)
    );
  };

  export let name = undefined;
  export let params = {};
  export let hash = undefined;
  export let query = undefined;
  export let state = null;

  $: url = router.url({ name, params, hash, query });
  $: target = $$restProps.target;

  function handleClick(event) {
    if (canNavigate(event, target)) {
      event.preventDefault();
      router.navigate({ url, state });
    }
  }
</script>

// packages/curi-react/src/Link.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';

const canNavigate = (event) => {
  return (
    !event.defaultPrevented &&
    event.button === 0 &&
    !(event.metaKey || event.altKey || event.ctrlKey || event.shiftKey)
  ) 
}

class Link extends Component {
  static propTypes = {
    name: PropTypes.string.isRequired,
    params: PropTypes.object,
    to: PropTypes.object
  }

  static contextTypes = {
    curi: PropTypes.object.isRequired
  }

  clickHandler = (event) => {
    if (canNavigate(event) && !this.props.target) {
      event.preventDefault();
      const { curi } = this.context;
      const { pathname } = this.state;
      const { to = {} } = this.props
      curi.history.push({ ...to, pathname })
    }
  }

  createPathname(props, context) {
    const { name, params } = props;
    const { curi } = context;
    const pathname = curi.addons.pathname(name, params);
    this.setState(() => ({
      pathname
    }));
  }

  componentWillMount() {
    this.createPathname(this.props, this.context);
  }

  componentWillReceiveProps(nextProps, nextContext) {
    this.createPathname(nextProps, nextContext);
  }

  render() {
    const { name, params, to, ...rest } = this.props;
    const { curi } = this.context;
    const { pathname } = this.state;
    const href = curi.history.createHref({ ...to, pathname });
    return (
      <a onClick={this.clickHandler} href={href} {...rest} />
    );
  }
}

export default Link;
